export const LOGIN = '/login'
export const SIGNUP = '/sign-up'
export const TODOS = '/todos'
export const COMPLETED_TODOS = '/completed-todos'
export const EDIT = '/update/:todoId'
export const CREATE_NEW = '/create/new'
export const ANY = '*'
